# Generated by Django 5.2.15 on 2026-06-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-created_at'], 'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='project_covers/', verbose_name='项目封面图'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='demo_url',
            field=models.URLField(blank=True, verbose_name='演示地址'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name='详细介绍'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='是否推荐'),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, unique=True, verbose_name='URL 标识'),
        ),
        migrations.AlterField(
            model_name='project',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='源码地址'),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.CharField(max_length=255, verbose_name='项目简述'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(blank=True, max_length=255, verbose_name='技术栈'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=160, verbose_name='项目名称'),
        ),
    ]
